name: Example action with Snyk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job Name
  snyk-pipeline:
    
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Running Snyk vuln check
        
      # Running Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: "\"code test"
          args: --sarif-file-output=snyk.sarif
