name: Example action with Snyk

on:
  # Triggers the workflow on push request event but only for the master branch
  push:
    branches: [ master ]

jobs:
  # Job Name
  snyk-pipeline:
    
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Running Snyk vuln check
        
      # Running Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
