name: Snyk Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  sast-scan:
    runs-on: ubuntu-latest
    name: Snyk Scans
    steps:     
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
